language: node_js

before_script:
  - npm install elm
  - export PATH="$PATH:$PWD/node_modules/elm/binwrappers/"

sudo: false

notifications:
  email: false

script:
  - elm # TODO

cache:
  directories:
    - elm-stuff
    - node_modules
